<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="/vacation" method="post">
    <input type="text" name="first_name" placeholder="First name">
    <input type="text" name="last_name" placeholder="Last name">
    <input type="text" name="course" placeholder="course">
    <input type="text" name="institute" placeholder="institute">
    <input type="submit">
</form>
</body>
</html>